language: rust
cache: cargo
os:
  - linux
  - osx
  - windows
dist: bionic
osx_image: xcode11.2
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - os: linux
      rust: nightly
    - os: osx
    - os: windows
  fast_finish: true
before_install:
  - rustup -v component add rustfmt
  - rustup -v component add clippy
env:
  global:
    - CARGO_INCREMENTAL=1
    - CARGO_CACHE_RUSTC_INFO=1
    - CARGO_BUILD_PIPELINING=true
script:
  - cargo -v fmt --all -- --check
  - cargo -v check --all --examples --tests --benches
  - cargo -v clippy --all --examples --tests --benches
  - cargo -v test --all
  - cargo -v bench --all
