version: '2.0'
services:
  memory_db:
    image: redis:5.0.9-buster
  db:
    image: postgres:12.4
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
  app:
    build:
      context: .
      args:
        - PORT
    environment:
      - PORT
      - DB_HOST
      - DB_USERNAME
      - DB_PASSWORD
      - DB_DATABASE
      - MEMORY_DB_HOST
      - MEMORY_DB_PORT
      - MEMORY_DB_USERNAME
      - MEMORY_DB_PASSWORD
      - BOOKER_PROVIDER
      - ETHEREUM_COLD_KEY
      - ETHEREUM_SIGN_KEY
      - WEB3_PROVIDER
      - WEB3_BATCH_SIZE
      - ETHEREUM_BLOCK_CHECK_TIME
      - ETHEREUM_BLOCK_TRY_CHECK_NUMBER
      - ETHEREUM_REQUIRED_CONFIRMATIONS
      - ETHEREUM_USDT_ADDRESS
      - BITSHARES_SIGN_KEY
      - BITSHARES_MEMO_KEY
      - BITSHARES_PROVIDER
      - BITSHARES_CONNECTION_TIMEOUT
      - BITSHARES_BLOCK_CHECK_TIME
      - BITSHARES_BLOCK_TRY_CHECK_NUMBER
      - BITSHARES_ASSET_FEE
    depends_on:
      - memory_db
      - db
    ports:
      - '8080:${PORT}'
